apiVersion: v1
kind: Service
metadata:
  name: backstage-auth
  namespace: backstage-auth
  labels:
    app: backstage-auth
spec:
  selector:
    app: backstage-auth
  ports:
  - port: 7007
    targetPort: 7007
    protocol: TCP


