apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-scheduler

resources:
- namespace.yaml
- kubectl-runner-rbac.yaml
- kubectl-runner-cluster-rbac.yaml
- task-scheduler-deployment.yaml
- task-scheduler-service.yaml
- business-hours-config.yaml
- protected-namespaces-configmap.yaml
- kyverno-namespace-scheduler-policies.yaml
- kyverno-force-spot-nodepool.yaml

labels:
- pairs:
    app.kubernetes.io/name: task-scheduler
    app.kubernetes.io/instance: task-scheduler
    app.kubernetes.io/managed-by: argocd