apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- task-scheduler-deployment.yaml
- task-scheduler-service.yaml
- kubectl-runner-rbac.yaml

commonLabels:
  app.kubernetes.io/name: task-scheduler
  app.kubernetes.io/instance: task-scheduler

images:
- name: task-scheduler-frontend
  newName: 226633502530.dkr.ecr.us-east-1.amazonaws.com/task-scheduler-frontend
  newTag: latest
- name: kubectl-runner
  newName: 226633502530.dkr.ecr.us-east-1.amazonaws.com/kubectl-runner
  newTag: latest