apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-scheduler

resources:
- namespace.yaml
- kubectl-runner-rbac.yaml
- task-scheduler-deployment.yaml
- task-scheduler-service.yaml

commonLabels:
  app.kubernetes.io/name: task-scheduler
  app.kubernetes.io/instance: task-scheduler
  app.kubernetes.io/managed-by: argocd