apiVersion: v1
kind: Namespace
metadata:
  name: task-scheduler
  labels:
    name: task-scheduler
    argocd.argoproj.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
